# Dev
org.gradle.jvmargs=-Xmx3G
org.gradle.caching=true
org.gradle.configureondemand=true
# If your computer can handle it, turn this to true
org.gradle.parallel=false
net.minecraftforge.gradle.merge-source-sets=true
# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false
fabric.loom.multiProjectOptimisation=true
# Mod
# The unique mod identifier for the mod. Must be lowercase in English locale. Must fit the regex [a-z][a-z0-9_]{1,63}
# Must match the String constant located in the main mod class annotated with @Mod.
mod.id=tectonic_plates
# The human-readable display name for the mod.
mod.name=Tectonic Plates
# The license of the mod. Review your options at https://choosealicense.com/. All Rights Reserved is the default.
mod.license=LGPL-3.0-or-later
# The mod version. See https://semver.org/
mod.version=0.1.0
# The group ID for the mod. It is only important when publishing as an artifact to a Maven repository.
# This should match the base package used for the mod sources.
# See https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod.group=io.codetoil
# The authors of the mod. This is a simple text string that is used for display purposes in the mod list.
mod.authors=Codetoil
# The description of the mod. This is a simple multiline text string that is used for display purposes in the mod list.
mod.description=Tectonic Plates is a Minecraft Mod that implements plate tectonics into the game.\n\n\n
mod.credits=*

license_statement=Tectonic Plates is a Minecraft Mod that implements plate tectonics into the game.\nCopyright (C) 2025-2026  Codetoil\n\nThis program is free software: you can redistribute it and/or modify\nit under the terms of the GNU Lesser General Public License as published by\nthe Free Software Foundation, either version 3 of the License, or\n(at your option) any later version.\n\nThis program is distributed in the hope that it will be useful,\nbut WITHOUT ANY WARRANTY; without even the implied warranty of\nMERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\nGNU Lesser General Public License for more details.\n\nYou should have received a copy of the GNU Lesser General Public License\nalong with this program.  If not, see https://www.gnu.org/licenses.

# Minecraft
minecraft_version=26.1
# Fabric https://fabricmc.net/develop/
fabric_loader_version=0.18.5
fabric_api_version=0.144.3+26.1
# MinecraftForge https://files.minecraftforge.net/net/minecraftforge/forge/
minecraftforge_version=62.0.9
minecraftforge_loader_version_range=[62,63)
minecraftforge_version_range=[62,63)
minecraftforge_eventbus_validator_version=7.0.1
# NeoForge https://projects.neoforged.net/neoforged/neoforge/
neoforge_version=26.1.0.15-beta
neoforge_version_range=[26.1.0,26.2.0)
java.version=25